name: 'amazon_ads_source'
version: '0.1.0'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

vars:
  amazon_ads_source:
    ad_group_history: "{{ source('amazon_ads','ad_group_history') }}"
    ad_group_level_report: "{{ source('amazon_ads','ad_group_level_report') }}"
    advertised_product_report: "{{ source('amazon_ads','advertised_product_report') }}"
    campaign_history: "{{ source('amazon_ads','campaign_history') }}"
    campaign_level_report: "{{ source('amazon_ads','campaign_level_report') }}"
    portfolio_history: "{{ source('amazon_ads','portfolio_history') }}"
    product_ad_history: "{{ source('amazon_ads','product_ad_history') }}"
    keyword_history: "{{ source('amazon_ads','keyword_history') }}"
    targeting_keyword_report: "{{ source('amazon_ads','targeting_keyword_report') }}"
    search_term_ad_keyword_report: "{{ source('amazon_ads','search_term_ad_keyword_report') }}"

models:
  amazon_ads_source:
    tmp:
      +materialized: view
    +materialized: table
    +schema: amazon_ads_source